import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QuizContextProvider } from "@/lib/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QuizContextProvider>
        <body className={`${inter.className} bg-black`}>{children}</body>
      </QuizContextProvider>
    </html>
  );
}
