import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QuizContextProvider } from "@/lib/globalContext";
import { Header } from "@/components/Header";
const poppins = Poppins({subsets:["latin"],weight:["400","500","900"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <QuizContextProvider>
          <body className={`${poppins.className} gradient_bg relative`}>
            <Header/>
            {children}
          </body>
        </QuizContextProvider>
    </html>
  );
}
